apiVersion: monitoring.googleapis.com/v1
kind: Rules
metadata:
  name: node-exporter-rules
  namespace: monitoring
spec:
  groups:
    - name: node-exporter
      rules:
        - alert: NodeExporterDown
          expr: up{job="node-exporter"} == 0
          for: 45s
          labels:
            severity: warning
          annotations:
            description: 'up{job="node-exporter", instance="{{ $labels.instance }}"} has been 0 for more than 45s'
